### ISSUE TITLE
Incorrect Submit calling

### ISSUE THREAD

**Issue by bvn13** [rma-consulting/react-xhr-uploader#13]
I have a form into HTML. I put XHRUploader with default settings inside this form. When I click Upload button, It seems that something like submitting of my form occures - URL becomes like: host/?param1=&param2=#react-hash instead of host/#/react-hash.

**Comment by harunhasdal** [comment]
This component does an XHR request, it wouldn't affect your URL parameters.

**Comment by bvn13** [comment]
Will check again.
