### ISSUE TITLE
xhr uploader

### ISSUE THREAD

**Issue by Subha** [rma-consulting/react-xhr-uploader#16]
Thank you for this nice Component. 

1. I am unable to drag and drop multiple files into the upload container. Any suggestions?
   <XHRUploader
        url={UPLOAD_URL}
        maxFiles={5}
      />

Any help is appreciated.

**Comment by harunhasdal** [comment]
Have you tried `maxFiles` property? If you do not specify, it defaults to one file.

**Comment by Subha** [comment]
Thanks for your response. 

Yes I used maxFiles property and that works only when I click button to upload multiple files. (i<nput type="file">). Unable to drag and drop multiple files.

**Comment by harunhasdal** [comment]
Can you share some code sample along with browser version you are using?

**Comment by Subha** [comment]
Thank you :)

const Demo = () => (

  <div style={{width:600}}>
    <article>
      <p>Default usage comes up with an upload button for manual instantiation of the upload and supports one file.</p>
      <XHRUploader
        url={UPLOAD_URL}
        dropzoneLabel="Drop the files here to upload "
        maxFiles={5}
      />

      <XHRUploader
        url={UPLOAD_URL}
        dropzoneLabel="Drop the files here to upload - DEMO"
        />


    </article>

  </div>
);

export default Demo;

I am testing in chrome browser  - 57.0.2987.110 (64-bit).

I noticed that the drag and dropping multiple files works in your DEMO link. Let me debug more.
