### ISSUE TITLE
How to change the text in buttons

### ISSUE THREAD

**Issue by shahjabeen-elevate** [rma-consulting/react-xhr-uploader#26]
I want to change the text that says 'Drag and drop your files...' or 'Upload' 
How to do that? @harunhasdal

**Comment by harunhasdal** [comment]
What you are looking for are the `props.buttonLabel`, this defaults to 'Upload'; and `props. dropzoneLabel `, this defaults to 'Drag and drop your files here or pick them from your computer'.

You can use them as below

```js
<XHRUploader
          url="http://localhost:3000/api/uploadfile"
          buttonLabel="Go"
          dropzoneLabel="Drag here"
        />
```
