### ISSUE TITLE
Invalid progress displayed for chunked files

### ISSUE THREAD

**Issue by donarus** [rma-consulting/react-xhr-uploader#5]
It seems that there is an issue with chunked uploader.

**PROBLEM:**
Problem is that it never shows 100% success

**REASON:**
there is invalid logic for computation of totalProgress in function _updateFileChunkProgress_ - we are **dividing reduced sum by number length of newProgressArr**, but **newProgressArr** always contains one zero element, pushed as _chunkProgress.push(0)_ in method filesToItems. From this reason we always end up with value < 100%

**SOLUTION:**
add-1 to divider in  _updateFileChunkProgress_ method

**Comment by donarus** [comment]
I'll prepare the PR

**Comment by donarus** [comment]
PR here ... https://github.com/rma-consulting/react-xhr-uploader/pull/6

**Comment by harunhasdal** [comment]
Merged in #6.

Released in 0.3.2.

**Comment by donarus** [comment]
@harunhasdal seems that the fix was not propagated to 0.3.2 version in NPM repository

**Comment by harunhasdal** [comment]
my bad, it was published before merge.

Released 0.3.3
